### ISSUE TITLE
[Select] Custom option schema + getOptionLabel + noResultsMsg prone to cause errors

### ISSUE THREAD

**Issue by schnerd** [uber-web/baseui#1026]
## Current Behavior

Using a custom option schema in conjunction with the `getOptionLabel` prop render a label that uses multiple properties from your object is pretty common. 

However, when using `noResultsMsg="..."` to render a pseudo-option when someone types a query that doesn't match, your getOptionLabel callback will be passed this pseudo-option which may not have the properties expected.

This results in a JavaScript error that unmounts your app (if you don't have error boundaries configured)

## How to replicate

CodeSandbox: https://codesandbox.io/s/7m18o9r73x
Type in random characters like "kxzckjvhasdf", app will unmount due to error.

## Expected Behavior

Base UI should take steps to protect users from this failure scenario

## Potential Solutions

1. Don't call `getOptionLabel` for the special No Results option. Downside is this may prevent people from being able to customize how this looks.
2. Switch to a `renderNoResults: () => Node` prop that is used instead of `noResultsMsg` (getOptionLabel wont be called here either)
3. Update the flow types for getOptionLabel to be `({option: OptionT | NoResultsOptionT}) => Node` where NoResultsOptionT is an exact object type. This has the downside that users who aren't using `noResultsMsg` will still have to do null checks since the flow type is stricter.

I probably lean towards number 2 but open to any other ideas you might have.

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
Tested this with flow checking and it seems to properly warn when I'm dangerously accessing a missing property. Is that coming up when importing the package as a dependency? 

<img width="500" alt="Screen Shot 2019-03-15 at 8 32 02 AM" src="https://user-images.githubusercontent.com/5317799/54442949-d7ef5500-46fc-11e9-9d48-4c667db01aa3.png">

I find that there's a lot to be gained from co-locating the label rendering to a single function call + if statement, rather than splitting up amongst two functions. Another option, that I think may be the best way forward, is to reconsider the 'no results' implementation itself. It should not repurpose the 'option' rendering at all. Overloading like in the `getOptionLabel` function leads to unexpected results/bugs where people will assume consistency. We have updated 'No Results' designs that suggest decoupling anyway. My suggestion is to move towards a styled-component/override approach, and possibly allow a `React.Node` for `noResultsMsg`

<img width="375" alt="Screen Shot 2019-03-15 at 8 43 15 AM" src="https://user-images.githubusercontent.com/5317799/54443884-d757be00-46fe-11e9-9703-7a83af0d6aff.png">

**Comment by schnerd** [comment]
> Tested this with flow checking and it seems to properly warn when I'm dangerously accessing a missing property. Is that coming up when importing the package as a dependency?

Interesting – I'm sort of reporting this on behalf of another engineer on the team, but I think the way our code is structured, the flowtype for this callback was getting lost, thus we weren't getting warned though.

Either way, I don't think it's unreasonable to allow Option with a custom schema. How else are we supposed to do custom rendering that uses a variety of fields (not just leveraging `labelKey`)? Theoretically it seems like Option should actually be a generic type for Select:

```
class Select<O> extends Component<PropsT<O>, SelectStateT> {
```

That way the param of getOptionLabel can exactly match the schema of the object the user is passing in. Seems like this works using a [quick and dirty test in try flow](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnAArFioAqAPAHkAfHAC8cAN504cCGBjAIAO1QAuOAIDaAXQA00uAHMsMAfMVKAMsgBGWADbqBYkdjwwAdADkIAEyz6AL70dLj2aOgAyg5Y+IIiWAAeMFhKvuhu+B4AwiSQSqkwfJxyvPEiUjKUaVhQABQAlJIGVSYArlBKcHUtMnB8mZ4AYlDIhiCFQr0yAJASMAAWwKgeYFwrcgrKKyDIYHWLy6vrHsam5srWdvYNgdP9APSDHiNjE0owU31wDfQyd3cGMxWHBsm1UDASGYtkoeGJmjJgL51BCoMAlIZ9DJwtcUTA0RisXAJjBkL5kKT1JU+gQIBA8QTDAYASFcNt4CAmNCLGpQeDISBucoeDp4ZoDBI4Ej1GRkGRdHAcQ4ZQBBeXEkxkinIKlwWn08g2ZBQMhwQJmomS6WG9VKxzkABC6pJWspkj1dJlRoAXqbzXdtCECG0lPgLMSmABxExCqy2Bx1TYWJrUygwDpdPi+YAANyEEiTyg8dvNdQLFyUHhd5NJHn1gQafAe2bzdEBbJU8BVYDA8MaLm6Bj40XssXghZUogknNjqHNZ1jVwcU850fOMKX9nNDymvyAA).

That said, that's a much broader change that is likely outside the scope of this issue. 

I agree with your proposed solution, sounds pretty close to what I was outlining in option number 2. 👍

**Comment by nadiia** [comment]
Added the no results state in here #1245 and closing this issue.
