### ISSUE TITLE
Datepicker preserves state/highlighted day when scrolling through months. 

### ISSUE THREAD

**Issue by lxe** [uber-web/baseui#1141]
## Current Behavior

![datepicker-highlights-state mov](https://user-images.githubusercontent.com/1486609/55909439-e7917a80-5b90-11e9-9789-2d7051f99f10.gif)

Should not preserve last highlighted day when scrolling

## Your Environment

https://codesandbox.io/embed/v6jxlxx5zl

- [X] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by IgorWilbert** [comment]
Hey @lxe ! Unless you plan to work on it, I'd be happy to take this issue. Thanks!

**Comment by jh3y** [comment]
I'm not sure about this as a UX issue.

If you have a start and end date, your next click **should** be your chosen start date.

Consider the scenario where you have two dates selected. You click a new date that you want to be the start. If the next click clears the date, you will have to click again to select it. Therefore, you are clicking twice in order to select a start date.

I think this one can be parked for now 👍

**Comment by gergelyke** [comment]
I think we should reopen this - if I am correct, Aleksey's comment was not about the clicks, but the fact that random days get highlighted when scrolling through days

**Comment by jh3y** [comment]
Correct @gergelyke 👍 Sorry for misinterpreting what was going on here 😅 
I've added a fix for this in PR #1437 by removing `setHighlightedDate` from the `onMonthChange` handler. This ensures that the random highlight doesn't appear on scroll 👍
