### ISSUE TITLE
[Accessibility] ARIA Improvement for Modal component

### ISSUE THREAD

**Issue by paschalidi** [uber-web/baseui#1236]
Hello 👋 🌸 everybody! Thanks for the amazing work you are going here and thanks for giving us such a nice project to look up to! 🏆 

As currently the modal functions, there might be some improvements to be made on the accessibility side. 
[I take w3 accessibility practises as guide](https://www.w3.org/TR/wai-aria-practices/#dialog_modal). Following the link we can see that in the section "Keyboard Interaction" are some points that can still be covered.

## Current Behavior

1. When a dialog opens, focus is not on an actionable element inside the dialog. 
2. Pressing `Tab` button when focus is on the last tabbable element inside the dialog, moves focus outside of the dialog.

## Expected Behavior
1. If focus is on the last tabbable element inside the dialog, moves focus to the first tabbable element inside the dialog. 
2. Pressing `Tab` button when a dialog opens, focus moves to an element inside the dialog. See notes below regarding initial focus placement.

Thanks for the amazing job people! Let me know if this makes sense!

**Comment by gergelyke** [comment]
thanks for the kind words, and for opening this issue @paschalidi !

I think it definitely makes sense - would you mind chiming in @schnerd ?

**Comment by schnerd** [comment]
@paschalidi Thanks for reporting this! We're definitely striving to follow w3 accessibility practices and it's possible that we missed out on a couple things.

> When a dialog opens, focus is not on an actionable element inside the dialog.

As of right now we shift focus to the dialog container element itself when it opens (https://github.com/uber-web/baseui/blob/master/src/modal/modal.js#L199). It's difficult for us to automatically shift focus to the "first tabbable element" because that may be an `input` or some other element rendered into the `Modal` body by users of Base UI. Due to this complexity we decided to just focus the dialog container itself and then let the user implement focus on their own if they need to.

That said, to may be possible to use document.querySelector to find the first focusable element in the modal [[1](https://gomakethings.com/how-to-get-the-first-and-last-focusable-elements-in-the-dom/)] and trigger a focus event on it. Any other alternative approaches you can recommend?

One other thing I noticed when testing this is that our current DOM structure makes the Close (X) button the first tabbable item in the dialog. That should maybe be fixed.

> Pressing Tab button when focus is on the last tabbable element inside the dialog, moves focus outside of the dialog.

This is a good catch – we probably need some logic that listens for focus/blur events while a modal is open and then loops focus back around to the first focusable element (related to strategy above).

**Comment by gergelyke** [comment]
Thanks David!

@paschalidi would you be interested in exploring how these items could be fixed? Also, looping in @nadiia as she worked on the LayerManager, that may be relevant here

**Comment by schnerd** [comment]
Could look to Blueprint or other libs for ideas here:
https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/overlay/overlay.tsx#L276
https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/overlay/overlay.tsx#L432

**Comment by brentertz** [comment]
I'll just leave these here...

* https://github.com/davidtheclark/focus-trap-react
* https://github.com/facebook/react/blob/master/packages/react-events/docs/FocusScope.md

**Comment by sandgraham** [comment]
We just landed some modal A11y enhancements in `v7.4.0` (#1406)! Thanks @paschalidi for bringing this to our attention.

In brief, we added focus trapping to the modal & when `autofocus` is true (the default) we focus the first interactive element.

**Comment by paschalidi** [comment]
Very sorry that I didnt have the time to work on this a little bit more. I would do next time for sure! 
Keep the great work up! the lib looks amazing
