### ISSUE TITLE
Pagination issue with onPageChange

### ISSUE THREAD

**Issue by hanweifish** [uber-web/baseui#404]
Pagination code here:

https://github.com/uber-web/baseui/blob/master/src/pagination/pagination.js#L79

Why put onPageChange and onNextClick trigger here both, if user set both, it will trigger twice. 
Should we only set onPageChange only?

**Comment by abmai** [comment]
Heya! Thanks for bringing this up.

This is intended behavior, since `onPageChange` is supposed to signal when the page is changing, and `onNextClick` etc is supposed to act as the `onClick` listener for the button itself. So there are two distinct events happening, the `currentPage` is changing **and** the button is being clicked on.

There's a different bug here though, we should be spreading `...args` when calling `onNextClick`...haha.

**Comment by gergelyke** [comment]
Thanks Anh!
