### ISSUE TITLE
Introduce BaseProvider

### ISSUE THREAD

**Issue by tajo** [uber-web/baseui#634]
Today, if you want to use BaseUI components you need to install Styletron as a separate dependency and set it up for yourself. This has two downsides:

- It creates an extra friction when starting with BaseUI.
- We (BaseUI team) don't have a control over the default settings for Styletron. For example, if we want to start supporting Android 4+ across the board, we can't do it just with a bump of BaseUI version but every user of BaseUI would have to change the Styletron configuration. This goes for bugfixes in Styletron as well.

* [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

```
yarn add baseui
```

```jsx
import {BaseProvider, styled} from 'baseui';
import {StatefulInput} from 'baseui/input';

const Centered = styled('div', {
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
  height: '100%',
});

export default function Hello() {
  return (
    <BaseProvider>
      <Centered>
        <StatefulInput />
      </Centered>
    </BaseProvider>
  );
}
```

`BaseProvider` makes some default assumptions (for example using `LightTheme`) but still provides props to customize:

- `engine` - custom Styletron setup/engine
- `theme` - when the LightTheme doesn't cut it

## Current Behavior

```
yarn add baseui styletron-react styletron-react-core styletron-standard styletron-engine-atomic
```

```jsx
import {Client as Styletron} from 'styletron-engine-atomic';
import {Provider as StyletronProvider} from 'styletron-react';
import {LightTheme, ThemeProvider, styled} from 'baseui';
import {StatefulInput} from 'baseui/input';

const engine = new Styletron();

const Centered = styled('div', {
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
  height: '100%',
});

export default function Hello() {
  return (
    <StyletronProvider value={engine}>
      <ThemeProvider theme={LightTheme}>
        <Centered>
          <StatefulInput />
        </Centered>
      </ThemeProvider>
    </StyletronProvider>
  );
}
```

## Note

Users of Fusion.js should still rely on [fusion-plugin-styletron-react](https://github.com/fusionjs/fusion-plugin-styletron-react) as a setup mechanism.

**Comment by rtsao** [comment]
Definitely agreed that extra dependencies introduces more friction.

At the very least, this should be slightly reduced after:
1. Because of changes in Flow 0.85, as of https://github.com/styletron/styletron/pull/279 `styletron-react-core` no longer serves a purpose so it has been deleted (and can be removed as a peer dependency from base UI).
2. https://github.com/uber-web/baseui/pull/635 is landed (styletron-standard doesn't need to be a peer dependency).

Unfortunately, even when using `BaseProvider`, because of [how React 16.3 context works](https://github.com/facebook/react/issues/13346), `styletron-react` will still need to be a peerDependency of BaseUI (to avoid problems with context) and hence users of BaseUI will still need to install `styletron-react` as a dependency 😕.

I hope eventually this peer dependency can be eliminated, but we'll need to figure out a workaround or alternative solution for ensuring context works correctly.
